### ISSUE TITLE
Pintar as guitarras

### ISSUE THREAD

**Issue by JPKP-Kuhn** [guitar-hero-luthier/guitar-hero-luthier#32]

**Comment by JPKP-Kuhn** [comment]
Guitarra V pronta, talvez mais alguns detalhes ainda

**Comment by JPKP-Kuhn** [comment]
Pintando guitarra Strato para ficar parecida com a do Eddie Van Halen

**Comment by joaovs2004** [comment]
Todas as três guitarras foram pintadas
